name: CI-COVERAGE

on:
  pull_request:
    types: [opened, synchronize, reopened]

  push:
    branches:
      - main


jobs:
  setup:
    name: Common Setup
    uses: seungjaey/nx-main-performance-playground/.github/workflows/common.yaml@main

  build:
    needs: [setup]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 14.16.1 ]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node.js Version - ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup NPM Cache
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: ${{ needs.setup.outputs.CACHE_PACKAGES_PATH }}
          key: ${{ needs.setup.outputs.CACHE_PACKAGES_KEY }}

      - name: Run Build
        run: npm run build